from enum import Enum


class RequestedParameter(Enum):

    REFERENCESWITCHHORIZONTALAXIS = 1
    LIGHTBARRIERINSIDE = 2
    LIGHTBARRIEROUTSIDE = 3
    REFERENCESWITCHVERTICALAXIS = 4
    HORIZONTALAXISSTEP = 5
    VERTICALAXISSTEP = 6
    REFERENCESWITCHCANTILEVERFRONT = 7
    REFERENCESWITCHCANTILEVERBACK = 8
    MOTORCONVEYORBELTFORWARD = 9
    MOTORCONVEYORBELTBACKWARD = 10
    MOTORVERTICALAXISDOWNWARD = 11
    MOTORVERTICALAXISUPWARD = 12
    MOTORCANTILEVERFORWARD = 13
    MOTORCANTILEVERBACKWARD = 14


    PUSHBUTTONSLIDER1FRONT= 15
    PUSHBUTTONSLIDER1REAR = 16
    PUSHBUTTONSLIDER2FRONT = 17
    PUSHBUTTONSLIDER2REAR = 18
    LIGHTBARRIERSLIDER1 = 19
    LIGHTBARRIERMILLINGMACHINE = 20
    LIGHTBARRIERLOADINGSTATION = 21
    LIGHTBARRIERDRILLINGMACHINE = 22
    LIGHTBARRIERCONVEYORBELTSWAP = 23
    MOTORSLIDER1BACKWARD = 24
    MOTORSLIDER1FORWARD = 25
    MOTORSLIDER2BACKWARD = 26
    MOTORSLIDER2FORWARD = 27
    MOTORCONVEYORBELTFEED = 28
    MOTORCONVEYORBELTMILLINGMACHINE = 29
    MOTORMILLINGMACHINE = 30
    MOTORCONVEYORBELTDRILLINGMACHINE = 31
    MOTORDRILLINGMACHINE = 32
    MOTORCONVEYORBELTSWAP = 33


    REFERENCESWITCHTURNTABLEPOSITIONVACUUM = 34
    REFERENCESWITCHTURNTABLEPOSITIONBELT = 35
    LIGHTBARRIERENDOFCONVEYORBELT = 36
    REFERENCESWITCHTURNTABLEPOSITIONSAW = 37
    REFERENCESWITCHVACUUMPOSITIONTURNTABLE = 38
    REFERENCESWITCHOVENFEEDERINSIDE = 39
    REFERENCESWITCHOVENFEEDEROUTSIDE = 40
    REFERENCESWITCHVACUUMPOSITIONOVEN = 41
    LIGHTBARRIEROVEN = 42
    MOTORTURNTABLECLOCKWISE = 43
    MOTORTURNTABLECOUNTERCLOCKWISE = 44
    MOTORSAW = 45
    MOTOROVENFEEDERRETRACT = 46
    MOTOROVENFEEDEREXTEND = 47
    MOTORVACUUMTOWARDSOVEN = 48
    MOTORVACUUMTOWARDSTURNTABLE = 49
    LIGHTOVEN = 50
    VALVEVACUUM = 51
    VALVELOWERING = 52
    VALVEOVENDOOR = 53
    VALVEFEEDER = 54


    PULSECOUNTER = 55
    LIGHTBARRIERINLET = 56
    LIGHTBARRIERBEHINDCOLORSENSOR = 57
    LIGHTBARRIERWHITE = 58
    LIGHTBARRIERRED = 59
    LIGHTBARRIERBLUE = 60
    MOTORCONVEYORBELT = 61
    COMPRESSOR = 62
    VALVEFIRSTEJECTORWHITE = 63
    VALVESECONDEJECTORRED = 64
    VALVETHIRDEJECTORBLUE = 65
    SENSCOLORDETECTOR = 66
    SENSBLUEDETECTOR = 68
    SENSREDDETECTOR = 69
    SENSWHITEDETECTOR = 70


    REFERENCESWITCHROTATE = 71

    ROTATESTEP = 72
    MOTORVERTICALAXISUP = 74
    MOTORVERTICALAXISDOWN = 73
    MOTORHORIZONTALAXISBACKWARD = 75
    MOTORHORIZONTALAXISFORWARD = 76
    MOTORROTATECOUNTERCLOCKWISE = 77
    MOTORROTATECLOCKWISE = 78

    LIGHTBARRIERFEEDSTATION = 79
    LIGHTBARRIERSWAPSTATION = 80

    LIGHTBARRIERGOODSINOUT = 81
    LIGHTBARRIERPUNCHINGMACHINE = 82
    SWITCHPUNCHINGMACHINEUP = 83
    SWITCHPUNCHINGMACHINEDOWN = 84
    MOTORPUNCHINGMACHINEUP = 85
    MOTORPUNCHINGMACHINEDOWN = 86


    REFERNCESWITCHCLAW = 87
    PULSECOUNTERGRIPPER = 88
    REFERENCESWITCHGRIPARM = 89
    PULSECOUNTERGRIPARM = 90
    MOTORGRIPPEROPEN = 91
    MOTORGRIPPERCLOSE = 92
    MOTORGRIPARMFORWARD = 93
    MOTORGRIPARMBACKWARD = 94

    ALL = 95
