<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.inria.test</groupId>
    <artifactId>simple-generation-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<java.version>21</java.version>

		<maven.api.version>3.9.6</maven.api.version>
		<maven.plugin.tools.version>3.11.0</maven.plugin.tools.version>
		<sirius.web.version>2026.3.0</sirius.web.version>
		<syson.version>2026.3.0</syson.version>
	</properties>
	
	<repositories>
		<repository>
			<id>central</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
		<repository>
			<id>github-sirius-emfjson</id>
			<url>https://maven.pkg.github.com/eclipse-sirius/sirius-emf-json</url>
		</repository>
		<repository>
			<id>github-sirius-web</id>
			<url>https://maven.pkg.github.com/eclipse-sirius/sirius-web</url>
		</repository>
		<repository>
			<id>github-syson</id>
			<url>https://maven.pkg.github.com/eclipse-syson/syson</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
            <groupId>@project.groupId@</groupId>
			<artifactId>sysml-mission-runtime</artifactId>
			<version>@project.version@</version>
		</dependency>
	</dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>@project.groupId@</groupId>
                <artifactId>@project.artifactId@</artifactId>
                <version>@project.version@</version>
               <executions>
                    <execution>
                    	<id>generate-sysml</id>
            			<phase>generate-sources</phase>
                        <goals>
                        	<goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <inputFiles>
                        <file>src/main/sysml/messages_def.sysml</file>
                        <file>src/main/sysml/zones_def.sysml</file>
                        <file>src/main/sysml/cb_def.sysml</file>
                    </inputFiles>
                    <basePackageName>fr.inria.mbdo.factory.generated</basePackageName>
                </configuration>
            </plugin>
        </plugins>
    </build>
    

</project>