FROM ros:humble
RUN apt update
RUN apt install -y python3-argcomplete python3-colcon-common-extensions libboost-system-dev build-essential
RUN apt install -y ros-humble-hls-lfcd-lds-driver
RUN apt install -y ros-humble-turtlebot3-msgs
RUN apt install -y ros-humble-dynamixel-sdk
RUN apt install -y libudev-dev
RUN apt install -y ros-humble-hardware-interface
