<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <groupId>fr.inria.mbdo.mission</groupId>
    <artifactId>sample-factoryscada-mission</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>


    <dependencies>
        <dependency>
            <groupId>fr.inria.mbdo.mission</groupId>
            <artifactId>sysml-mission-runtime</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>fr.inria.mbdo.mission</groupId>
                <artifactId>sysml-mission-generator-maven-plugin</artifactId>
                <version>1.0.0-SNAPSHOT</version>
                <!-- <executions>
                    <execution>
                        <id>generate-sysml</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions> -->
                <configuration>
                    <inputFiles>
                        <file>../missions-design-models/common/common_def.sysml</file>
                        <file>../missions-design-models/common/zones_def.sysml</file>
                        <file>../missions-design-models/TEST-MACHINE/test-machine_def.sysml</file>
                        <file>../missions-design-models/TEST-MACHINE/test-machine_missions_def.sysml</file>
                    </inputFiles>
                    <basePackageName>fr.inria.mbdo.factory.generated</basePackageName>
                </configuration>
            </plugin>

            <plugin> <!-- not mandatory but may help some IDE such as eclipse-->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>target/generated-sources/sysml</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>