= WebSocket Protocols of factoryscada backend

== Topics overview

[cols="1,1,1"]
|===
| Implementing class | Incoming topic | Outgoing topic 

|SortingLineController.executeEjectCommand()
|<<incoming_sortingline-machinename-command-eject,/sortingLine/{machineName}/command/eject>>
|  

|SortingLineController.handleUnmappedMessage()
|<<incoming_sortingline,/sortingLine**>>
|  

|SortingLineController.receiveStopCommand()
|<<incoming_sortingline-machinename-command-stop,/sortingLine/{machineName}/command/stop>>
|  

|SortingLineController.receiveDebugCommand()
|<<incoming_sortingline-machinename-command-debug,/sortingLine/{machineName}/command/debug>>
|  

|SortingLineController.getMachineStatus()
|<<incoming_sortingline-machinename-machine-status,/sortingLine/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|SortingLineController.getCommandStatus()
|<<incoming_sortingline-machinename-command-status,/sortingLine/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|FactoryScadaController.getFactoryInstance()
|<<incoming_factory-instance,/factory/instance>>
|<<outgoing_topic-factory-instance,/topic/factory-instance>>

|FactoryScadaController.handleUnmappedMessage()
|<<incoming_factory,/factory**>>
|  

|FactoryScadaController.getFactoryConfiguration()
|<<incoming_factory-configuration,/factory/configuration>>
|<<outgoing_topic-factory-configuration,/topic/factory-configuration>>

|FactoryScadaController.getCommandPlaceholder()
|<<incoming_factory-placeholder,/factory/placeholder>>
|<<outgoing_topic-command-placeholder,/topic/command-placeholder>>

|MultiProcessingStationController.executeSetupCommand()
|<<incoming_multiprocessingstation-machinename-command-setup,/multiProcessingStation/{machineName}/command/setup>>
|  

|MultiProcessingStationController.executeArmMoveCommand()
|<<incoming_multiprocessingstation-machinename-command-arm-move,/multiProcessingStation/{machineName}/command/arm_move>>
|  

|MultiProcessingStationController.executeConveyorMoveOutCommand()
|<<incoming_multiprocessingstation-machinename-command-conveyor-move-out,/multiProcessingStation/{machineName}/command/conveyor_move_out>>
|  

|MultiProcessingStationController.executeTurntableEjectCommand()
|<<incoming_multiprocessingstation-machinename-command-turntable-eject,/multiProcessingStation/{machineName}/command/turntable_eject>>
|  

|MultiProcessingStationController.receiveStopCommand()
|<<incoming_multiprocessingstation-machinename-command-stop,/multiProcessingStation/{machineName}/command/stop>>
|  

|MultiProcessingStationController.receiveDebugCommand()
|<<incoming_multiprocessingstation-machinename-command-debug,/multiProcessingStation/{machineName}/command/debug>>
|  

|MultiProcessingStationController.executeTurntableRotateCommand()
|<<incoming_multiprocessingstation-machinename-command-turntable-rotate,/multiProcessingStation/{machineName}/command/turntable_rotate>>
|  

|MultiProcessingStationController.executeMoveToSafePositionCommand()
|<<incoming_multiprocessingstation-machinename-command-move-to-safe-position,/multiProcessingStation/{machineName}/command/move_to_safe_position>>
|  

|MultiProcessingStationController.executeOvenHeatCommand()
|<<incoming_multiprocessingstation-machinename-command-oven-heat,/multiProcessingStation/{machineName}/command/oven_heat>>
|  

|MultiProcessingStationController.executeOvenProcessCommand()
|<<incoming_multiprocessingstation-machinename-command-oven-process,/multiProcessingStation/{machineName}/command/oven_process>>
|  

|MultiProcessingStationController.executeArmPlaceCommand()
|<<incoming_multiprocessingstation-machinename-command-arm-place,/multiProcessingStation/{machineName}/command/arm_place>>
|  

|MultiProcessingStationController.executeConveyorMoveToSensorCommand()
|<<incoming_multiprocessingstation-machinename-command-conveyor-move-to-sensor,/multiProcessingStation/{machineName}/command/conveyor_move_to_sensor>>
|  

|MultiProcessingStationController.getCommandStatus()
|<<incoming_multiprocessingstation-machinename-command-status,/multiProcessingStation/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|MultiProcessingStationController.executeProcessCommand()
|<<incoming_multiprocessingstation-machinename-command-process,/multiProcessingStation/{machineName}/command/process>>
|  

|MultiProcessingStationController.executeSawCutCommand()
|<<incoming_multiprocessingstation-machinename-command-saw-cut,/multiProcessingStation/{machineName}/command/saw_cut>>
|  

|MultiProcessingStationController.handleUnmappedMessage()
|<<incoming_multiprocessingstation,/multiProcessingStation**>>
|  

|MultiProcessingStationController.executeOvenUnloadCommand()
|<<incoming_multiprocessingstation-machinename-command-oven-unload,/multiProcessingStation/{machineName}/command/oven_unload>>
|  

|MultiProcessingStationController.executeArmPickCommand()
|<<incoming_multiprocessingstation-machinename-command-arm-pick,/multiProcessingStation/{machineName}/command/arm_pick>>
|  

|MultiProcessingStationController.getMachineStatus()
|<<incoming_multiprocessingstation-machinename-machine-status,/multiProcessingStation/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|MultiProcessingStationController.executeOvenLoadCommand()
|<<incoming_multiprocessingstation-machinename-command-oven-load,/multiProcessingStation/{machineName}/command/oven_load>>
|  

|MultiProcessingStationController.executeProcess1Command()
|<<incoming_multiprocessingstation-machinename-command-process1,/multiProcessingStation/{machineName}/command/process1>>
|  

|ConveyorBeltController.handleUnmappedMessage()
|<<incoming_conveyorbelt,/conveyorBelt**>>
|  

|ConveyorBeltController.receiveMoveNbStepsCommand()
|<<incoming_conveyorbelt-machinename-command-move-nb-steps,/conveyorBelt/{machineName}/command/move_nb_steps>>
|  

|ConveyorBeltController.receiveStopCommand()
|<<incoming_conveyorbelt-machinename-command-stop,/conveyorBelt/{machineName}/command/stop>>
|  

|ConveyorBeltController.receiveDebugCommand()
|<<incoming_conveyorbelt-machinename-command-debug,/conveyorBelt/{machineName}/command/debug>>
|  

|ConveyorBeltController.getMachineStatus()
|<<incoming_conveyorbelt-machinename-machine-status,/conveyorBelt/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|ConveyorBeltController.receiveMoveCommand()
|<<incoming_conveyorbelt-machinename-command-move-out,/conveyorBelt/{machineName}/command/move_out>>
|  

|ConveyorBeltController.receiveMoveToSensorCommand()
|<<incoming_conveyorbelt-machinename-command-move-to-sensor,/conveyorBelt/{machineName}/command/move_to_sensor>>
|  

|ConveyorBeltController.getCommandStatus()
|<<incoming_conveyorbelt-machinename-command-status,/conveyorBelt/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|PlcController.getPlcConnectionStatus()
|<<incoming_plc-plcname-plc-connection,/plc/{plcName}/plc-connection>>
|<<outgoing_topic-plcname-plc-connection-status,/topic/{plcName}/plc-connection-status>>

|PlcController.handleUnmappedMessage()
|<<incoming_plc,/plc**>>
|  

|IndexedLineController.receiveMoveToMillCommand()
|<<incoming_indexedline-machinename-command-move-to-mill,/indexedLine/{machineName}/command/move_to_mill>>
|  

|IndexedLineController.receiveMillCommand()
|<<incoming_indexedline-machinename-command-mill,/indexedLine/{machineName}/command/mill>>
|  

|IndexedLineController.receiveMoveToDrillCommand()
|<<incoming_indexedline-machinename-command-move-to-drill,/indexedLine/{machineName}/command/move_to_drill>>
|  

|IndexedLineController.handleUnmappedMessage()
|<<incoming_indexedline,/indexedLine**>>
|  

|IndexedLineController.receiveStopCommand()
|<<incoming_indexedline-machinename-command-stop,/indexedLine/{machineName}/command/stop>>
|  

|IndexedLineController.receiveDebugCommand()
|<<incoming_indexedline-machinename-command-debug,/indexedLine/{machineName}/command/debug>>
|  

|IndexedLineController.getMachineStatus()
|<<incoming_indexedline-machinename-machine-status,/indexedLine/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|IndexedLineController.receiveDrillCommand()
|<<incoming_indexedline-machinename-command-drill,/indexedLine/{machineName}/command/drill>>
|  

|IndexedLineController.receiveMoveToOutputCommand()
|<<incoming_indexedline-machinename-command-move-to-output,/indexedLine/{machineName}/command/move_to_output>>
|  

|IndexedLineController.receiveProcess1Command()
|<<incoming_indexedline-machinename-command-process1,/indexedLine/{machineName}/command/process1>>
|  

|IndexedLineController.getCommandStatus()
|<<incoming_indexedline-machinename-command-status,/indexedLine/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|VacuumGripperController.executeSetupCommand()
|<<incoming_vacuumgripper-machinename-command-setup,/vacuumGripper/{machineName}/command/setup>>
|  

|VacuumGripperController.executePickCommand()
|<<incoming_vacuumgripper-machinename-command-pick,/vacuumGripper/{machineName}/command/pick>>
|  

|VacuumGripperController.executeStatusRequest()
|<<incoming_vacuumgripper-machinename-request-status,/vacuumGripper/{machineName}/request/status>>
|  

|VacuumGripperController.executeOrderedMoveToCommand()
|<<incoming_vacuumgripper-machinename-command-ordered-move-to,/vacuumGripper/{machineName}/command/ordered_move_to>>
|  

|VacuumGripperController.executePlaceCommand()
|<<incoming_vacuumgripper-machinename-command-place,/vacuumGripper/{machineName}/command/place>>
|  

|VacuumGripperController.executeRetractArmCommand()
|<<incoming_vacuumgripper-machinename-command-retract-arm,/vacuumGripper/{machineName}/command/retract_arm>>
|  

|VacuumGripperController.receiveDebugCommand()
|<<incoming_vacuumgripper-machinename-command-debug,/vacuumGripper/{machineName}/command/debug>>
|  

|VacuumGripperController.executeMoveToSafePositionCommand()
|<<incoming_vacuumgripper-machinename-command-move-to-safe-position,/vacuumGripper/{machineName}/command/move_to_safe_position>>
|  

|VacuumGripperController.executeReleaseCommand()
|<<incoming_vacuumgripper-machinename-command-release,/vacuumGripper/{machineName}/command/release>>
|  

|VacuumGripperController.executeMoveCommand()
|<<incoming_vacuumgripper-machinename-command-move,/vacuumGripper/{machineName}/command/move>>
|  

|VacuumGripperController.getCommandStatus()
|<<incoming_vacuumgripper-machinename-command-status,/vacuumGripper/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|VacuumGripperController.handleUnmappedMessage()
|<<incoming_vacuumgripper,/vacuumGripper**>>
|  

|VacuumGripperController.executeStopCommand()
|<<incoming_vacuumgripper-machinename-command-stop,/vacuumGripper/{machineName}/command/stop>>
|  

|VacuumGripperController.executeGripCommand()
|<<incoming_vacuumgripper-machinename-command-grip,/vacuumGripper/{machineName}/command/grip>>
|  

|VacuumGripperController.getMachineStatus()
|<<incoming_vacuumgripper-machinename-machine-status,/vacuumGripper/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|VacuumGripperController.executeGoToPositionCommand()
|<<incoming_vacuumgripper-machinename-command-go-to-position,/vacuumGripper/{machineName}/command/go_to_position>>
|  

|LogsWebSocketController.requestFrontendLogs()
|<<incoming_logs-request,/logs/request>>
|  

|HighBayWarehouseController.executeSetupCommand()
|<<incoming_highbaywarehouse-machinename-command-setup,/highBayWarehouse/{machineName}/command/setup>>
|  

|HighBayWarehouseController.receiveDebugCommand()
|<<incoming_highbaywarehouse-machinename-command-debug,/highBayWarehouse/{machineName}/command/debug>>
|  

|HighBayWarehouseController.executeConveyorBackwardCommand()
|<<incoming_highbaywarehouse-machinename-command-conveyor-backward,/highBayWarehouse/{machineName}/command/conveyor_backward>>
|  

|HighBayWarehouseController.executePickupFromCommand()
|<<incoming_highbaywarehouse-machinename-command-pickup-from,/highBayWarehouse/{machineName}/command/pickup_from>>
|  

|HighBayWarehouseController.executeMoveToSafePositionCommand()
|<<incoming_highbaywarehouse-machinename-command-move-to-safe-position,/highBayWarehouse/{machineName}/command/move_to_safe_position>>
|  

|HighBayWarehouseController.executeGoToRowCommand()
|<<incoming_highbaywarehouse-machinename-command-go-to-row,/highBayWarehouse/{machineName}/command/go_to_row>>
|  

|HighBayWarehouseController.executeHorizontalToCommand()
|<<incoming_highbaywarehouse-machinename-command-horizontal-to,/highBayWarehouse/{machineName}/command/horizontal_to>>
|  

|HighBayWarehouseController.getCommandStatus()
|<<incoming_highbaywarehouse-machinename-command-status,/highBayWarehouse/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|HighBayWarehouseController.handleUnmappedMessage()
|<<incoming_highbaywarehouse,/highBayWarehouse**>>
|  

|HighBayWarehouseController.executeCantileverBackwardCommand()
|<<incoming_highbaywarehouse-machinename-command-cantilever-backward,/highBayWarehouse/{machineName}/command/cantilever_backward>>
|  

|HighBayWarehouseController.executeStopCommand()
|<<incoming_highbaywarehouse-machinename-command-stop,/highBayWarehouse/{machineName}/command/stop>>
|  

|HighBayWarehouseController.executeGoToColumnCommand()
|<<incoming_highbaywarehouse-machinename-command-go-to-column,/highBayWarehouse/{machineName}/command/go_to_column>>
|  

|HighBayWarehouseController.getMachineStatus()
|<<incoming_highbaywarehouse-machinename-machine-status,/highBayWarehouse/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|HighBayWarehouseController.executeConveyorStopCommand()
|<<incoming_highbaywarehouse-machinename-command-conveyor-stop,/highBayWarehouse/{machineName}/command/conveyor_stop>>
|  

|HighBayWarehouseController.executeStoreToCommand()
|<<incoming_highbaywarehouse-machinename-command-store-to,/highBayWarehouse/{machineName}/command/store_to>>
|  

|HighBayWarehouseController.executeCantileverFrontendCommand()
|<<incoming_highbaywarehouse-machinename-command-cantilever-forward,/highBayWarehouse/{machineName}/command/cantilever_forward>>
|  

|HighBayWarehouseController.executeConveyorFrontendCommand()
|<<incoming_highbaywarehouse-machinename-command-conveyor-forward,/highBayWarehouse/{machineName}/command/conveyor_forward>>
|  

|HighBayWarehouseController.executeVerticalToCommand()
|<<incoming_highbaywarehouse-machinename-command-vertical-to,/highBayWarehouse/{machineName}/command/vertical_to>>
|  

|MissionOrchestratorController.stopMission()
|<<incoming_factorymission-command-stop,/factoryMission/command/stop>>
|  

|MissionOrchestratorController.startMission()
|<<incoming_factorymission-command-start-missionname,/factoryMission/command/start/{missionName}>>
|  

|MissionOrchestratorController.getMissionList()
|<<incoming_factorymission-list,/factoryMission/list>>
|<<outgoing_topic-mission-configuration,/topic/mission-configuration>>

|MissionOrchestratorController.handleUnmappedMessage()
|<<incoming_factorymission,/factoryMission**>>
|  

|MissionOrchestratorController.getFactoryMissionsConfiguration()
|<<incoming_factorymission-mission-configuration,/factoryMission/mission-configuration>>
|<<outgoing_topic-mission-configuration,/topic/mission-configuration>>

|MissionOrchestratorController.getFactoryActualMissions()
|<<incoming_factorymission-actual-command-executing,/factoryMission/actual-command-executing>>
|<<outgoing_topic-actual-command-executing,/topic/actual-command-executing>>

|MissionOrchestratorController.getMissionStatus()
|<<incoming_factorymission-status,/factoryMission/status>>
|<<outgoing_topic-mission-status,/topic/mission-status>>

|PunchingMachineController.handleUnmappedMessage()
|<<incoming_punchingmachine,/punchingMachine**>>
|  

|PunchingMachineController.receiveStopCommand()
|<<incoming_punchingmachine-machinename-command-stop,/punchingMachine/{machineName}/command/stop>>
|  

|PunchingMachineController.receiveDebugCommand()
|<<incoming_punchingmachine-machinename-command-debug,/punchingMachine/{machineName}/command/debug>>
|  

|PunchingMachineController.getMachineStatus()
|<<incoming_punchingmachine-machinename-machine-status,/punchingMachine/{machineName}/machine-status>>
|<<outgoing_topic-machinename-machine-status,/topic/{machineName}/machine-status>>

|PunchingMachineController.receivePunchCommand()
|<<incoming_punchingmachine-machinename-command-punch,/punchingMachine/{machineName}/command/punch>>
|  

|PunchingMachineController.getCommandStatus()
|<<incoming_punchingmachine-machinename-command-status,/punchingMachine/{machineName}/command-status>>
|<<outgoing_topic-machinename-command-status,/topic/{machineName}/command-status>>

|WebSocketPublisher.sendMachineStatus()
| 
|/topic/{machineName}/machine-status
|WebSocketPublisher.sendPlcStatus()
| 
|/topic/{controllerName}/plc-connection-status
|WebSocketPublisher.sendCommandStatus()
| 
|/topic/{machineName}/command-status
|WebSocketPublisher.sendFrontendLogs()
| 
|/topic/frontend-logs
|WebSocketPublisher.sendControllerFeedback()
| 
|/topic/controller-feedbacks
|===

== Incoming Topics

[[incoming_conveyorbelt-machinename-command-move-to-sensor]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_to_sensor`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveToSensorCommand()`

==== Parameters

- `machineName` (String)
- `moveToLightBarrierDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_conveyorbelt-machinename-command-move-nb-steps]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_nb_steps`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveNbStepsCommand()`

==== Parameters

- `machineName` (String)
- `moveStepsDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_conveyorbelt-machinename-command-move-out]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_out`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveCommand()`

==== Parameters

- `machineName` (String)
- `moveOutDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_conveyorbelt-machinename-command-stop]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_conveyorbelt-machinename-command-debug]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_conveyorbelt-machinename-command-status]]
===  Incoming Topic: `/conveyorBelt/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_conveyorbelt-machinename-machine-status]]
===  Incoming Topic: `/conveyorBelt/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_conveyorbelt]]
===  Incoming Topic: `/conveyorBelt**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_factory-placeholder]]
===  Incoming Topic: `/factory/placeholder`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getCommandPlaceholder()`

*Send To:* `/topic/command-placeholder`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "additionalProperties" : {
    "type" : "object",
    "id" : "urn:jsonschema:java:lang:Object"
  }
}
----

[[incoming_factory-configuration]]
===  Incoming Topic: `/factory/configuration`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryConfiguration()`

*Send To:* `/topic/factory-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "mqttHost" : {
      "type" : "string"
    },
    "controllers" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "host" : {
            "type" : "string"
          },
          "commandPort" : {
            "type" : "integer"
          },
          "notificationPort" : {
            "type" : "integer"
          },
          "machines" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration:MachineConfiguration",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "type" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[incoming_factory-instance]]
===  Incoming Topic: `/factory/instance`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryInstance()`

*Send To:* `/topic/factory-instance`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaInstance",
  "properties" : {
    "controllers" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol",
        "properties" : {
          "sendChannelConnected" : {
            "type" : "boolean"
          },
          "receivedChannelConnected" : {
            "type" : "boolean"
          }
        }
      }
    },
    "machines" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:AbstractMachine",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "protocol" : {
            "type" : "object",
            "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol"
          },
          "rawCommandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "commandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}
----

[[incoming_factory]]
===  Incoming Topic: `/factory**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-cantilever-backward]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/cantilever_backward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeCantileverBackwardCommand()`

==== Parameters

- `machineName` (String)
- `cantilever_backwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-cantilever-forward]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/cantilever_forward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeCantileverFrontendCommand()`

==== Parameters

- `machineName` (String)
- `cantilever_forwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-conveyor-backward]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_backward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorBackwardCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_backwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-conveyor-forward]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_forward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorFrontendCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_forwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-conveyor-stop]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorStopCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-go-to-column]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/go_to_column`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeGoToColumnCommand()`

==== Parameters

- `machineName` (String)
- `go_to_columnDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-go-to-row]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/go_to_row`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeGoToRowCommand()`

==== Parameters

- `machineName` (String)
- `go_to_rowDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-horizontal-to]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/horizontal_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeHorizontalToCommand()`

==== Parameters

- `machineName` (String)
- `horizontal_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-pickup-from]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/pickup_from`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executePickupFromCommand()`

==== Parameters

- `machineName` (String)
- `pickup_fromDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-setup]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-stop]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-store-to]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/store_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeStoreToCommand()`

==== Parameters

- `machineName` (String)
- `dto` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-vertical-to]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/vertical_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeVerticalToCommand()`

==== Parameters

- `machineName` (String)
- `vertical_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-move-to-safe-position]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-debug]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_highbaywarehouse-machinename-command-status]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_highbaywarehouse-machinename-machine-status]]
===  Incoming Topic: `/highBayWarehouse/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_highbaywarehouse]]
===  Incoming Topic: `/highBayWarehouse**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-stop]]
===  Incoming Topic: `/indexedLine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-move-to-mill]]
===  Incoming Topic: `/indexedLine/{machineName}/command/move_to_mill`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveMoveToMillCommand()`

==== Parameters

- `machineName` (String)
- `moveToMillDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-mill]]
===  Incoming Topic: `/indexedLine/{machineName}/command/mill`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveMillCommand()`

==== Parameters

- `machineName` (String)
- `millDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-drill]]
===  Incoming Topic: `/indexedLine/{machineName}/command/drill`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveDrillCommand()`

==== Parameters

- `machineName` (String)
- `drillDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-move-to-drill]]
===  Incoming Topic: `/indexedLine/{machineName}/command/move_to_drill`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveMoveToDrillCommand()`

==== Parameters

- `machineName` (String)
- `moveToDrillDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-move-to-output]]
===  Incoming Topic: `/indexedLine/{machineName}/command/move_to_output`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveMoveToOutputCommand()`

==== Parameters

- `machineName` (String)
- `moveToOutputDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-process1]]
===  Incoming Topic: `/indexedLine/{machineName}/command/process1`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveProcess1Command()`

==== Parameters

- `machineName` (String)
- `process1DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-debug]]
===  Incoming Topic: `/indexedLine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_indexedline-machinename-command-status]]
===  Incoming Topic: `/indexedLine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_indexedline-machinename-machine-status]]
===  Incoming Topic: `/indexedLine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_indexedline]]
===  Incoming Topic: `/indexedLine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_factorymission-command-start-missionname]]
===  Incoming Topic: `/factoryMission/command/start/{missionName}`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.startMission()`

==== Parameters

- `missionName` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_factorymission-command-stop]]
===  Incoming Topic: `/factoryMission/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.stopMission()`

==== Parameters


NOTE: This endpoint does not send a response back via a topic.

[[incoming_factorymission-mission-configuration]]
===  Incoming Topic: `/factoryMission/mission-configuration`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryMissionsConfiguration()`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:FactoryMissionsParallelized_dto",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:MissionParallelized_dto",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "nodes" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto",
              "properties" : {
                "type" : {
                  "type" : "string"
                },
                "outputNodes" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto"
                  }
                },
                "id" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "outputs" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[incoming_factorymission-actual-command-executing]]
===  Incoming Topic: `/factoryMission/actual-command-executing`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryActualMissions()`

*Send To:* `/topic/actual-command-executing`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "array"
}
----

[[incoming_factorymission-status]]
===  Incoming Topic: `/factoryMission/status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionStatus()`

*Send To:* `/topic/mission-status`

==== Parameters


==== Response Payload

class java.lang.String

[[incoming_factorymission-list]]
===  Incoming Topic: `/factoryMission/list`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionList()`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:FactoryMissionsParallelized_dto",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:MissionParallelized_dto",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "nodes" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto",
              "properties" : {
                "type" : {
                  "type" : "string"
                },
                "outputNodes" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto"
                  }
                },
                "id" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "outputs" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[incoming_factorymission]]
===  Incoming Topic: `/factoryMission**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-stop]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-setup]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-move-to-safe-position]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-process1]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/process1`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeProcess1Command()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-process]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/process`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeProcessCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-oven-load]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/oven_load`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeOvenLoadCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-oven-unload]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/oven_unload`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeOvenUnloadCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-oven-heat]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/oven_heat`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeOvenHeatCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-oven-process]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/oven_process`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeOvenProcessCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-arm-move]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/arm_move`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeArmMoveCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-arm-pick]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/arm_pick`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeArmPickCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-arm-place]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/arm_place`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeArmPlaceCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-turntable-rotate]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/turntable_rotate`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeTurntableRotateCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-turntable-eject]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/turntable_eject`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeTurntableEjectCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-conveyor-move-to-sensor]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/conveyor_move_to_sensor`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeConveyorMoveToSensorCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-conveyor-move-out]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/conveyor_move_out`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeConveyorMoveOutCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-saw-cut]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/saw_cut`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeSawCutCommand()`

==== Parameters

- `machineName` (String)
- `DTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-debug]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_multiprocessingstation-machinename-command-status]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_multiprocessingstation-machinename-machine-status]]
===  Incoming Topic: `/multiProcessingStation/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_multiprocessingstation]]
===  Incoming Topic: `/multiProcessingStation**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_plc]]
===  Incoming Topic: `/plc**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_plc-plcname-plc-connection]]
===  Incoming Topic: `/plc/{plcName}/plc-connection`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.getPlcConnectionStatus()`

*Send To:* `/topic/{plcName}/plc-connection-status`

==== Parameters

- `plcName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}
----

[[incoming_punchingmachine-machinename-command-stop]]
===  Incoming Topic: `/punchingMachine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_punchingmachine-machinename-command-punch]]
===  Incoming Topic: `/punchingMachine/{machineName}/command/punch`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receivePunchCommand()`

==== Parameters

- `machineName` (String)
- `punchDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_punchingmachine-machinename-command-debug]]
===  Incoming Topic: `/punchingMachine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_punchingmachine-machinename-command-status]]
===  Incoming Topic: `/punchingMachine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_punchingmachine-machinename-machine-status]]
===  Incoming Topic: `/punchingMachine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_punchingmachine]]
===  Incoming Topic: `/punchingMachine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_sortingline-machinename-command-stop]]
===  Incoming Topic: `/sortingLine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_sortingline-machinename-command-eject]]
===  Incoming Topic: `/sortingLine/{machineName}/command/eject`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.executeEjectCommand()`

==== Parameters

- `machineName` (String)
- `ejectDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_sortingline-machinename-command-debug]]
===  Incoming Topic: `/sortingLine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_sortingline-machinename-command-status]]
===  Incoming Topic: `/sortingLine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_sortingline-machinename-machine-status]]
===  Incoming Topic: `/sortingLine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_sortingline]]
===  Incoming Topic: `/sortingLine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-setup]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-stop]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-move-to-safe-position]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-move]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/move`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeMoveCommand()`

==== Parameters

- `machineName` (String)
- `moveDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-place]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/place`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executePlaceCommand()`

==== Parameters

- `machineName` (String)
- `placeDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-pick]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/pick`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executePickCommand()`

==== Parameters

- `machineName` (String)
- `pickDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-go-to-position]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/go_to_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeGoToPositionCommand()`

==== Parameters

- `machineName` (String)
- `goToPositionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-request-status]]
===  Incoming Topic: `/vacuumGripper/{machineName}/request/status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeStatusRequest()`

==== Parameters

- `machineName` (String)
- `statusDTO` (GenericMachineStatusRequestDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineStatusRequestDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:RequestMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "requestId" : {
          "type" : "string"
        },
        "params" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "REFERENCESWITCHHORIZONTALAXIS", "LIGHTBARRIERINSIDE", "LIGHTBARRIEROUTSIDE", "REFERENCESWITCHVERTICALAXIS", "HORIZONTALAXISSTEP", "VERTICALAXISSTEP", "REFERENCESWITCHCANTILEVERFRONT", "REFERENCESWITCHCANTILEVERBACK", "MOTORCONVEYORBELTFORWARD", "MOTORCONVEYORBELTBACKWARD", "MOTORVERTICALAXISDOWNWARD", "MOTORVERTICALAXISUPWARD", "MOTORCANTILEVERFORWARD", "MOTORCANTILEVERBACKWARD", "PUSHBUTTONSLIDER1FRONT", "PUSHBUTTONSLIDER1REAR", "PUSHBUTTONSLIDER2FRONT", "PUSHBUTTONSLIDER2REAR", "LIGHTBARRIERSLIDER1", "LIGHTBARRIERMILLINGMACHINE", "LIGHTBARRIERLOADINGSTATION", "LIGHTBARRIERDRILLINGMACHINE", "LIGHTBARRIERCONVEYORBELTSWAP", "MOTORSLIDER1BACKWARD", "MOTORSLIDER1FORWARD", "MOTORSLIDER2BACKWARD", "MOTORSLIDER2FORWARD", "MOTORCONVEYORBELTFEED", "MOTORCONVEYORBELTMILLINGMACHINE", "MOTORMILLINGMACHINE", "MOTORCONVEYORBELTDRILLINGMACHINE", "MOTORDRILLINGMACHINE", "MOTORCONVEYORBELTSWAP", "REFERENCESWITCHTURNTABLEPOSITIONVACUUM", "REFERENCESWITCHTURNTABLEPOSITIONBELT", "LIGHTBARRIERENDOFCONVEYORBELT", "REFERENCESWITCHTURNTABLEPOSITIONSAW", "REFERENCESWITCHVACUUMPOSITIONTURNTABLE", "REFERENCESWITCHOVENFEEDERINSIDE", "REFERENCESWITCHOVENFEEDEROUTSIDE", "REFERENCESWITCHVACUUMPOSITIONOVEN", "LIGHTBARRIEROVEN", "MOTORTURNTABLECLOCKWISE", "MOTORTURNTABLECOUNTERCLOCKWISE", "MOTORSAW", "MOTOROVENFEEDERRETRACT", "MOTOROVENFEEDEREXTEND", "MOTORVACUUMTOWARDSOVEN", "MOTORVACUUMTOWARDSTURNTABLE", "LIGHTOVEN", "VALVEVACUUM", "VALVELOWERING", "VALVEOVENDOOR", "VALVEFEEDER", "PULSECOUNTER", "LIGHTBARRIERINLET", "LIGHTBARRIERBEHINDCOLORSENSOR", "LIGHTBARRIERWHITE", "LIGHTBARRIERRED", "LIGHTBARRIERBLUE", "MOTORCONVEYORBELT", "COMPRESSOR", "VALVEFIRSTEJECTORWHITE", "VALVESECONDEJECTORRED", "VALVETHIRDEJECTORBLUE", "REFERENCESWITCHROTATE", "ROTATESTEP", "MOTORVERTICALAXISUP", "MOTORVERTICALAXISDOWN", "MOTORHORIZONTALAXISBACKWARD", "MOTORHORIZONTALAXISFORWARD", "MOTORROTATECLOCKWISE", "MOTORROTATECOUNTERCLOCKWISE", "LIGHTBARRIERFEEDSTATION", "LIGHTBARRIERSWAPSTATION", "LIGHTBARRIERGOODSINOUT", "LIGHTBARRIERPUNCHINGMACHINE", "SWITCHPUNCHINGMACHINEUP", "SWITCHPUNCHINGMACHINEDOWN", "MOTORPUNCHINGMACHINEUP", "MOTORPUNCHINGMACHINEDOWN", "REFERNCESWITCHCLAW", "PULSECOUNTERGRIPPER", "REFERENCESWITCHGRIPARM", "PULSECOUNTERGRIPARM", "MOTORGRIPPEROPEN", "MOTORGRIPPERCLOSE", "MOTORGRIPARMFORWARD", "MOTORGRIPARMBACKWARD", "ALL" ]
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-grip]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/grip`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeGripCommand()`

==== Parameters

- `machineName` (String)
- `gripDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-release]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/release`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeReleaseCommand()`

==== Parameters

- `machineName` (String)
- `releaseDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-retract-arm]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/retract_arm`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeRetractArmCommand()`

==== Parameters

- `machineName` (String)
- `retract_armDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-ordered-move-to]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/ordered_move_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeOrderedMoveToCommand()`

==== Parameters

- `machineName` (String)
- `ordered_move_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED", "MPSOUTPUT", "MPSARMPOSITION", "MPSTURNTABLEPOSITION" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-debug]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_vacuumgripper-machinename-command-status]]
===  Incoming Topic: `/vacuumGripper/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_vacuumgripper-machinename-machine-status]]
===  Incoming Topic: `/vacuumGripper/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[incoming_vacuumgripper]]
===  Incoming Topic: `/vacuumGripper**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

[[incoming_logs-request]]
===  Incoming Topic: `/logs/request`

Declared in `io.github.mbdo.factoryscada.frontend.WebSocketPublisher$LogsWebSocketController.requestFrontendLogs()`

==== Parameters


NOTE: This endpoint does not send a response back via a topic.

== Outgoing Topics


=== Outgoing Topic: `/topic/controller-feedbacks`
_Broadcasts raw feedback from the controller_

Payload: `String`
{
  "type" : "string"
}

=== Outgoing Topic: `/topic/frontend-logs`
_All logs that should appear in the frontend_

Payload: `String`
{
  "type" : "string"
}

=== Outgoing Topic: `/topic/{controllerName}/plc-connection-status`
_Broadcasts PLC connection status updates_

Payload: `PlcConnectionStatusDto`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}

=== Outgoing Topic: `/topic/{machineName}/command-status`
_Broadcasts Command status updates_

Payload: `CommandStatusDTO`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}

=== Outgoing Topic: `/topic/{machineName}/machine-status`
_Broadcasts Machine status updates_

Payload: `CommandStatusDTO`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/conveyorBelt/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/conveyorBelt/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-command-placeholder]]
=== Outgoing Topic: `/topic/command-placeholder`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getCommandPlaceholder()`

*Request Mapping:* `@MessageMapping("/factory/placeholder")`

*Send To:* `/topic/command-placeholder`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "additionalProperties" : {
    "type" : "object",
    "id" : "urn:jsonschema:java:lang:Object"
  }
}
----

[[outgoing_topic-factory-configuration]]
=== Outgoing Topic: `/topic/factory-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryConfiguration()`

*Request Mapping:* `@MessageMapping("/factory/configuration")`

*Send To:* `/topic/factory-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "mqttHost" : {
      "type" : "string"
    },
    "controllers" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "host" : {
            "type" : "string"
          },
          "commandPort" : {
            "type" : "integer"
          },
          "notificationPort" : {
            "type" : "integer"
          },
          "machines" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration:MachineConfiguration",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "type" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[outgoing_topic-factory-instance]]
=== Outgoing Topic: `/topic/factory-instance`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryInstance()`

*Request Mapping:* `@MessageMapping("/factory/instance")`

*Send To:* `/topic/factory-instance`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaInstance",
  "properties" : {
    "controllers" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol",
        "properties" : {
          "sendChannelConnected" : {
            "type" : "boolean"
          },
          "receivedChannelConnected" : {
            "type" : "boolean"
          }
        }
      }
    },
    "machines" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:AbstractMachine",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "protocol" : {
            "type" : "object",
            "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol"
          },
          "rawCommandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "commandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/highBayWarehouse/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/highBayWarehouse/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/indexedLine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/indexedLine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-mission-configuration]]
=== Outgoing Topic: `/topic/mission-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryMissionsConfiguration()`

*Request Mapping:* `@MessageMapping("/factoryMission/mission-configuration")`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:FactoryMissionsParallelized_dto",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:MissionParallelized_dto",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "nodes" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto",
              "properties" : {
                "type" : {
                  "type" : "string"
                },
                "outputNodes" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto"
                  }
                },
                "id" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "outputs" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[outgoing_topic-actual-command-executing]]
=== Outgoing Topic: `/topic/actual-command-executing`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryActualMissions()`

*Request Mapping:* `@MessageMapping("/factoryMission/actual-command-executing")`

*Send To:* `/topic/actual-command-executing`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "array"
}
----

[[outgoing_topic-mission-status]]
=== Outgoing Topic: `/topic/mission-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionStatus()`

*Request Mapping:* `@MessageMapping("/factoryMission/status")`

*Send To:* `/topic/mission-status`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "string"
}
----

[[outgoing_topic-mission-configuration]]
=== Outgoing Topic: `/topic/mission-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionList()`

*Request Mapping:* `@MessageMapping("/factoryMission/list")`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:FactoryMissionsParallelized_dto",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:MissionParallelized_dto",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "nodes" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto",
              "properties" : {
                "type" : {
                  "type" : "string"
                },
                "outputNodes" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:mission:dtos:Node_dto"
                  }
                },
                "id" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "outputs" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/multiProcessingStation/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/multiProcessingStation/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-plcname-plc-connection-status]]
=== Outgoing Topic: `/topic/{plcName}/plc-connection-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.getPlcConnectionStatus()`

*Request Mapping:* `@MessageMapping("/plc/{plcName}/plc-connection")`

*Send To:* `/topic/{plcName}/plc-connection-status`

==== Parameters

- `plcName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/punchingMachine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/punchingMachine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/sortingLine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/sortingLine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-command-status]]
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/vacuumGripper/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

[[outgoing_topic-machinename-machine-status]]
=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/vacuumGripper/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

