= WebSocket Protocols of factoryscada backend

== Topics overview

[cols="1,1,1"]
|===
| Implementing class | Incoming topic | Outgoing topic 

|SortingLineController.executeEjectCommand()
|/sortingLine/{machineName}/command/eject
|  

|SortingLineController.handleUnmappedMessage()
|/sortingLine**
|  

|SortingLineController.receiveStopCommand()
|/sortingLine/{machineName}/command/stop
|  

|SortingLineController.receiveDebugCommand()
|/sortingLine/{machineName}/command/debug
|  

|SortingLineController.getMachineStatus()
|/sortingLine/{machineName}/machine-status
|/topic/{machineName}/machine-status

|SortingLineController.getCommandStatus()
|/sortingLine/{machineName}/command-status
|/topic/{machineName}/command-status

|FactoryScadaController.getFactoryInstance()
|/factory/instance
|/topic/factory-instance

|FactoryScadaController.handleUnmappedMessage()
|/factory**
|  

|FactoryScadaController.getFactoryConfiguration()
|/factory/configuration
|/topic/factory-configuration

|FactoryScadaController.getCommandPlaceholder()
|/factory/placeholder
|/topic/command-placeholder

|MultiProcessingStationController.executeSetupCommand()
|/multiProcessingStation/{machineName}/command/setup
|  

|MultiProcessingStationController.handleUnmappedMessage()
|/multiProcessingStation**
|  

|MultiProcessingStationController.receiveStopCommand()
|/multiProcessingStation/{machineName}/command/stop
|  

|MultiProcessingStationController.receiveDebugCommand()
|/multiProcessingStation/{machineName}/command/debug
|  

|MultiProcessingStationController.getMachineStatus()
|/multiProcessingStation/{machineName}/machine-status
|/topic/{machineName}/machine-status

|MultiProcessingStationController.executeMoveToSafePositionCommand()
|/multiProcessingStation/{machineName}/command/move_to_safe_position
|  

|MultiProcessingStationController.executeProcess1Command()
|/multiProcessingStation/{machineName}/command/process1
|  

|MultiProcessingStationController.getCommandStatus()
|/multiProcessingStation/{machineName}/command-status
|/topic/{machineName}/command-status

|ConveyorBeltController.handleUnmappedMessage()
|/conveyorBelt**
|  

|ConveyorBeltController.receiveMoveNbStepsCommand()
|/conveyorBelt/{machineName}/command/move_nb_steps
|  

|ConveyorBeltController.receiveStopCommand()
|/conveyorBelt/{machineName}/command/stop
|  

|ConveyorBeltController.receiveDebugCommand()
|/conveyorBelt/{machineName}/command/debug
|  

|ConveyorBeltController.getMachineStatus()
|/conveyorBelt/{machineName}/machine-status
|/topic/{machineName}/machine-status

|ConveyorBeltController.receiveMoveCommand()
|/conveyorBelt/{machineName}/command/move_out
|  

|ConveyorBeltController.receiveMoveToSensorCommand()
|/conveyorBelt/{machineName}/command/move_to_sensor
|  

|ConveyorBeltController.getCommandStatus()
|/conveyorBelt/{machineName}/command-status
|/topic/{machineName}/command-status

|PlcController.getPlcConnectionStatus()
|/plc/{plcName}/plc-connection
|/topic/{plcName}/plc-connection-status

|PlcController.handleUnmappedMessage()
|/plc**
|  

|IndexedLineController.handleUnmappedMessage()
|/indexedLine**
|  

|IndexedLineController.receiveStopCommand()
|/indexedLine/{machineName}/command/stop
|  

|IndexedLineController.receiveDebugCommand()
|/indexedLine/{machineName}/command/debug
|  

|IndexedLineController.getMachineStatus()
|/indexedLine/{machineName}/machine-status
|/topic/{machineName}/machine-status

|IndexedLineController.receiveMoveCommand()
|/indexedLine/{machineName}/command/process1
|  

|IndexedLineController.getCommandStatus()
|/indexedLine/{machineName}/command-status
|/topic/{machineName}/command-status

|VacuumGripperController.executeSetupCommand()
|/vacuumGripper/{machineName}/command/setup
|  

|VacuumGripperController.executePickCommand()
|/vacuumGripper/{machineName}/command/pick
|  

|VacuumGripperController.executeStatusRequest()
|/vacuumGripper/{machineName}/request/status
|  

|VacuumGripperController.executeOrderedMoveToCommand()
|/vacuumGripper/{machineName}/command/ordered_move_to
|  

|VacuumGripperController.executePlaceCommand()
|/vacuumGripper/{machineName}/command/place
|  

|VacuumGripperController.executeRetractArmCommand()
|/vacuumGripper/{machineName}/command/retract_arm
|  

|VacuumGripperController.receiveDebugCommand()
|/vacuumGripper/{machineName}/command/debug
|  

|VacuumGripperController.executeMoveToSafePositionCommand()
|/vacuumGripper/{machineName}/command/move_to_safe_position
|  

|VacuumGripperController.executeReleaseCommand()
|/vacuumGripper/{machineName}/command/release
|  

|VacuumGripperController.executeMoveCommand()
|/vacuumGripper/{machineName}/command/move
|  

|VacuumGripperController.getCommandStatus()
|/vacuumGripper/{machineName}/command-status
|/topic/{machineName}/command-status

|VacuumGripperController.handleUnmappedMessage()
|/vacuumGripper**
|  

|VacuumGripperController.executeStopCommand()
|/vacuumGripper/{machineName}/command/stop
|  

|VacuumGripperController.executeGripCommand()
|/vacuumGripper/{machineName}/command/grip
|  

|VacuumGripperController.getMachineStatus()
|/vacuumGripper/{machineName}/machine-status
|/topic/{machineName}/machine-status

|VacuumGripperController.executeGoToPositionCommand()
|/vacuumGripper/{machineName}/command/go_to_position
|  

|HighBayWarehouseController.executeSetupCommand()
|/highBayWarehouse/{machineName}/command/setup
|  

|HighBayWarehouseController.receiveDebugCommand()
|/highBayWarehouse/{machineName}/command/debug
|  

|HighBayWarehouseController.executeConveyorBackwardCommand()
|/highBayWarehouse/{machineName}/command/conveyor_backward
|  

|HighBayWarehouseController.executeMoveToSafePositionCommand()
|/highBayWarehouse/{machineName}/command/move_to_safe_position
|  

|HighBayWarehouseController.executeGoToRowCommand()
|/highBayWarehouse/{machineName}/command/go_to_row
|  

|HighBayWarehouseController.executeHorizontalToCommand()
|/highBayWarehouse/{machineName}/command/horizontal_to
|  

|HighBayWarehouseController.getCommandStatus()
|/highBayWarehouse/{machineName}/command-status
|/topic/{machineName}/command-status

|HighBayWarehouseController.handleUnmappedMessage()
|/highBayWarehouse**
|  

|HighBayWarehouseController.executeCantileverBackwardCommand()
|/highBayWarehouse/{machineName}/command/cantilever_backward
|  

|HighBayWarehouseController.executeRetrieveCommand()
|/highBayWarehouse/{machineName}/command/retrieve
|  

|HighBayWarehouseController.executeStopCommand()
|/highBayWarehouse/{machineName}/command/stop
|  

|HighBayWarehouseController.executeGoToColumnCommand()
|/highBayWarehouse/{machineName}/command/go_to_column
|  

|HighBayWarehouseController.getMachineStatus()
|/highBayWarehouse/{machineName}/machine-status
|/topic/{machineName}/machine-status

|HighBayWarehouseController.executeConveyorStopCommand()
|/highBayWarehouse/{machineName}/command/conveyor_stop
|  

|HighBayWarehouseController.executeCantileverFrontendCommand()
|/highBayWarehouse/{machineName}/command/cantilever_forward
|  

|HighBayWarehouseController.executeConveyorFrontendCommand()
|/highBayWarehouse/{machineName}/command/conveyor_forward
|  

|HighBayWarehouseController.executeVerticalToCommand()
|/highBayWarehouse/{machineName}/command/vertical_to
|  

|HighBayWarehouseController.executeStoreCommand()
|/highBayWarehouse/{machineName}/command/store
|  

|MissionOrchestratorController.stopMission()
|/factoryMission/command/stop
|  

|MissionOrchestratorController.startMission()
|/factoryMission/command/start/{missionName}
|  

|MissionOrchestratorController.getMissionList()
|/factoryMission/list
|/topic/mission-configuration

|MissionOrchestratorController.handleUnmappedMessage()
|/factoryMission**
|  

|MissionOrchestratorController.getFactoryMissionsConfiguration()
|/factoryMission/mission-configuration
|/topic/mission-configuration

|MissionOrchestratorController.getMissionStatus()
|/factoryMission/status
|/topic/mission-status

|PunchingMachineController.handleUnmappedMessage()
|/punchingMachine**
|  

|PunchingMachineController.receiveStopCommand()
|/punchingMachine/{machineName}/command/stop
|  

|PunchingMachineController.receiveDebugCommand()
|/punchingMachine/{machineName}/command/debug
|  

|PunchingMachineController.getMachineStatus()
|/punchingMachine/{machineName}/machine-status
|/topic/{machineName}/machine-status

|PunchingMachineController.receivePunchCommand()
|/punchingMachine/{machineName}/command/punch
|  

|PunchingMachineController.getCommandStatus()
|/punchingMachine/{machineName}/command-status
|/topic/{machineName}/command-status

|WebSocketPublisher.sendMachineStatus()
| 
|/topic/{machineName}/machine-status
|WebSocketPublisher.sendPlcStatus()
| 
|/topic/{controllerName}/plc-connection-status
|WebSocketPublisher.sendCommandStatus()
| 
|/topic/{machineName}/command-status
|WebSocketPublisher.sendControllerFeedback()
| 
|/topic/controller-feedbacks
|===

== Incoming Topics

===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_nb_steps`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveNbStepsCommand()`

==== Parameters

- `machineName` (String)
- `moveStepsDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_out`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveCommand()`

==== Parameters

- `machineName` (String)
- `moveOutDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/conveyorBelt/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/conveyorBelt/{machineName}/command/move_to_sensor`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveMoveToSensorCommand()`

==== Parameters

- `machineName` (String)
- `moveToLightBarrierDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/conveyorBelt/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/conveyorBelt/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/conveyorBelt/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/conveyorBelt**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/factory/placeholder`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getCommandPlaceholder()`

*Send To:* `/topic/command-placeholder`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "additionalProperties" : {
    "type" : "object",
    "id" : "urn:jsonschema:java:lang:Object"
  }
}
----

===  Incoming Topic: `/factory/configuration`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryConfiguration()`

*Send To:* `/topic/factory-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "controllers" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "host" : {
            "type" : "string"
          },
          "commandPort" : {
            "type" : "integer"
          },
          "notificationPort" : {
            "type" : "integer"
          },
          "machines" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration:MachineConfiguration",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "type" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

===  Incoming Topic: `/factory/instance`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryInstance()`

*Send To:* `/topic/factory-instance`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaInstance",
  "properties" : {
    "controllers" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol",
        "properties" : {
          "sendChannelConnected" : {
            "type" : "boolean"
          },
          "receivedChannelConnected" : {
            "type" : "boolean"
          }
        }
      }
    },
    "machines" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:AbstractMachine",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "protocol" : {
            "type" : "object",
            "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol"
          },
          "rawCommandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "commandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}
----

===  Incoming Topic: `/factory**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/cantilever_backward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeCantileverBackwardCommand()`

==== Parameters

- `machineName` (String)
- `cantilever_backwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/cantilever_forward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeCantileverFrontendCommand()`

==== Parameters

- `machineName` (String)
- `cantilever_forwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_backward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorBackwardCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_backwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_forward`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorFrontendCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_forwardDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/conveyor_stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeConveyorStopCommand()`

==== Parameters

- `machineName` (String)
- `conveyor_stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/go_to_column`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeGoToColumnCommand()`

==== Parameters

- `machineName` (String)
- `go_to_columnDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/go_to_row`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeGoToRowCommand()`

==== Parameters

- `machineName` (String)
- `go_to_rowDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/horizontal_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeHorizontalToCommand()`

==== Parameters

- `machineName` (String)
- `horizontal_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/retrieve`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeRetrieveCommand()`

==== Parameters

- `machineName` (String)
- `retrieveDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/store`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeStoreCommand()`

==== Parameters

- `machineName` (String)
- `storeDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/vertical_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeVerticalToCommand()`

==== Parameters

- `machineName` (String)
- `vertical_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/highBayWarehouse/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/highBayWarehouse/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/highBayWarehouse**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/indexedLine/{machineName}/command/process1`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveMoveCommand()`

==== Parameters

- `machineName` (String)
- `moveOutDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/indexedLine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/indexedLine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/indexedLine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/indexedLine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/indexedLine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/factoryMission/mission-configuration`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryMissionsConfiguration()`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:MissionConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "commands" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:Command",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "placeholder" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

===  Incoming Topic: `/factoryMission/command/start/{missionName}`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.startMission()`

==== Parameters

- `missionName` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/factoryMission/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.stopMission()`

==== Parameters


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/factoryMission/status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionStatus()`

*Send To:* `/topic/mission-status`

==== Parameters


==== Response Payload

class java.lang.String

===  Incoming Topic: `/factoryMission/list`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionList()`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:MissionConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "commands" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:Command",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "placeholder" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

===  Incoming Topic: `/factoryMission**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command/process1`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeProcess1Command()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/multiProcessingStation/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/multiProcessingStation/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/multiProcessingStation**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/plc**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/plc/{plcName}/plc-connection`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.getPlcConnectionStatus()`

*Send To:* `/topic/{plcName}/plc-connection-status`

==== Parameters

- `plcName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}
----

===  Incoming Topic: `/punchingMachine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/punchingMachine/{machineName}/command/punch`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receivePunchCommand()`

==== Parameters

- `machineName` (String)
- `punchDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/punchingMachine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/punchingMachine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/punchingMachine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/punchingMachine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/sortingLine/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.receiveStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/sortingLine/{machineName}/command/eject`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.executeEjectCommand()`

==== Parameters

- `machineName` (String)
- `ejectDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/sortingLine/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/sortingLine/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/sortingLine/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/sortingLine**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/setup`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeSetupCommand()`

==== Parameters

- `machineName` (String)
- `setupDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/stop`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeStopCommand()`

==== Parameters

- `machineName` (String)
- `stopDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/move_to_safe_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeMoveToSafePositionCommand()`

==== Parameters

- `machineName` (String)
- `move_to_safe_positionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/move`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeMoveCommand()`

==== Parameters

- `machineName` (String)
- `moveDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/pick`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executePickCommand()`

==== Parameters

- `machineName` (String)
- `pickDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/place`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executePlaceCommand()`

==== Parameters

- `machineName` (String)
- `placeDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/go_to_position`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeGoToPositionCommand()`

==== Parameters

- `machineName` (String)
- `goToPositionDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/request/status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeStatusRequest()`

==== Parameters

- `machineName` (String)
- `statusDTO` (GenericMachineStatusRequestDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineStatusRequestDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:RequestMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "requestId" : {
          "type" : "string"
        },
        "params" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "REFERENCESWITCHHORIZONTALAXIS", "LIGHTBARRIERINSIDE", "LIGHTBARRIEROUTSIDE", "REFERENCESWITCHVERTICALAXIS", "HORIZONTALAXISSTEP", "VERTICALAXISSTEP", "REFERENCESWITCHCANTILEVERFRONT", "REFERENCESWITCHCANTILEVERBACK", "MOTORCONVEYORBELTFORWARD", "MOTORCONVEYORBELTBACKWARD", "MOTORVERTICALAXISDOWNWARD", "MOTORVERTICALAXISUPWARD", "MOTORCANTILEVERFORWARD", "MOTORCANTILEVERBACKWARD", "PUSHBUTTONSLIDER1FRONT", "PUSHBUTTONSLIDER1REAR", "PUSHBUTTONSLIDER2FRONT", "PUSHBUTTONSLIDER2REAR", "LIGHTBARRIERSLIDER1", "LIGHTBARRIERMILLINGMACHINE", "LIGHTBARRIERLOADINGSTATION", "LIGHTBARRIERDRILLINGMACHINE", "LIGHTBARRIERCONVEYORBELTSWAP", "MOTORSLIDER1BACKWARD", "MOTORSLIDER1FORWARD", "MOTORSLIDER2BACKWARD", "MOTORSLIDER2FORWARD", "MOTORCONVEYORBELTFEED", "MOTORCONVEYORBELTMILLINGMACHINE", "MOTORMILLINGMACHINE", "MOTORCONVEYORBELTDRILLINGMACHINE", "MOTORDRILLINGMACHINE", "MOTORCONVEYORBELTSWAP", "REFERENCESWITCHTURNTABLEPOSITOINVACUUM", "REFERENCESWITCHTURNTABLEPOSITIONBELT", "LIGHTBARRIERENDOFCONVEYORBELT", "REFERENCESWITCHTURNTABLEPOSITIONSAW", "REFERENCESWITCHVACUUMPOSITIONTURNTABLE", "REFERENCESWITCHOVENFEEDERINSIDE", "REFERENCESWITCHOVENFEEDEROUTSIDE", "REFERENCESWITCHVACUUMPOSITIONOVEN", "LIGHTBARRIEROVEN", "MOTORTURNTABLECLOCKWISE", "MOTORTURNTABLECOUNTERCLOCKWISE", "MOTORSAW", "MOTOROVENFEEDERRETRACT", "MOTOROVENFEEDEREXTEND", "MOTORVACUUMTOWARDSOVEN", "MOTORVACUUMTOWARDSTURNTABLE", "LIGHTOVEN", "VALVEVACUUM", "VALVELOWERING", "VALVEOVENDOOR", "VALVEFEEDER", "PULSECOUNTER", "LIGHTBARRIERINLET", "LIGHTBARRIERBEHINDCOLORSENSOR", "LIGHTBARRIERWHITE", "LIGHTBARRIERRED", "LIGHTBARRIERBLUE", "MOTORCONVEYORBELT", "COMPRESSOR", "VALVEFIRSTEJECTORWHITE", "VALVESECONDEJECTORRED", "VALVETHIRDEJECTORBLUE", "REFERENCESWITCHROTATE", "ROTATESTEP", "MOTORVERTICALAXISUP", "MOTORVERTICALAXISDOWN", "MOTORHORIZONTALAXISBACKWARD", "MOTORHORIZONTALAXISFORWARD", "MOTORROTATECLOCKWISE", "MOTORROTATECOUNTERCLOCKWISE", "LIGHTBARRIERFEEDSTATION", "LIGHTBARRIERSWAPSTATION", "LIGHTBARRIERGOODSINOUT", "LIGHTBARRIERPUNCHINGMACHINE", "SWITCHPUNCHINGMACHINEUP", "SWITCHPUNCHINGMACHINEDOWN", "MOTORPUNCHINGMACHINEUP", "MOTORPUNCHINGMACHINEDOWN", "REFERNCESWITCHCLAW", "PULSECOUNTERGRIPPER", "REFERENCESWITCHGRIPARM", "PULSECOUNTERGRIPARM", "MOTORGRIPPEROPEN", "MOTORGRIPPERCLOSE", "MOTORGRIPARMFORWARD", "MOTORGRIPARMBACKWARD", "ALL" ]
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/grip`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeGripCommand()`

==== Parameters

- `machineName` (String)
- `gripDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/release`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeReleaseCommand()`

==== Parameters

- `machineName` (String)
- `releaseDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/retract_arm`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeRetractArmCommand()`

==== Parameters

- `machineName` (String)
- `retract_armDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/ordered_move_to`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.executeOrderedMoveToCommand()`

==== Parameters

- `machineName` (String)
- `ordered_move_toDTO` (GenericMachineCommandDTO)

==== Request Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:GenericMachineCommandDTO",
  "properties" : {
    "topicName" : {
      "type" : "string"
    },
    "timestamp" : {
      "type" : "string"
    },
    "message" : {
      "type" : "object",
      "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:CommandMessage",
      "properties" : {
        "jsonType" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "outputId" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "parameters" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:dtos:Parameter",
            "properties" : {
              "passableType" : {
                "type" : "string",
                "enum" : [ "COLOR", "DIRECTION", "BOXNUMBER", "POSITIONPARAMETERTHREED", "NUMBERNATURAL", "AXISPRIORITIZED" ]
              },
              "passable" : {
                "type" : "object",
                "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:Passable"
              }
            }
          }
        }
      }
    }
  }
}
----


NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command/debug`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.receiveDebugCommand()`

==== Parameters

- `machineName` (String)
- `message` (String)

NOTE: This endpoint does not send a response back via a topic.

===  Incoming Topic: `/vacuumGripper/{machineName}/command-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getCommandStatus()`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/vacuumGripper/{machineName}/machine-status`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getMachineStatus()`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

===  Incoming Topic: `/vacuumGripper**`

Declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.handleUnmappedMessage()`

==== Parameters

- `destination` (String)
- `messageContent` (String)

NOTE: This endpoint does not send a response back via a topic.

== Outgoing Topics


=== Outgoing Topic: `/topic/controller-feedbacks`
_Broadcasts raw feedback from the controller_

Payload: `String`
{
  "type" : "string"
}

=== Outgoing Topic: `/topic/{controllerName}/plc-connection-status`
_Broadcasts PLC connection status updates_

Payload: `PlcConnectionStatusDto`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}

=== Outgoing Topic: `/topic/{machineName}/command-status`
_Broadcasts Command status updates_

Payload: `CommandStatusDTO`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}

=== Outgoing Topic: `/topic/{machineName}/machine-status`
_Broadcasts Machine status updates_

Payload: `CommandStatusDTO`
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/conveyorBelt/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.ConveyorBeltController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/conveyorBelt/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/command-placeholder`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getCommandPlaceholder()`

*Request Mapping:* `@MessageMapping("/factory/placeholder")`

*Send To:* `/topic/command-placeholder`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "additionalProperties" : {
    "type" : "object",
    "id" : "urn:jsonschema:java:lang:Object"
  }
}
----

=== Outgoing Topic: `/topic/factory-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryConfiguration()`

*Request Mapping:* `@MessageMapping("/factory/configuration")`

*Send To:* `/topic/factory-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "controllers" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "host" : {
            "type" : "string"
          },
          "commandPort" : {
            "type" : "integer"
          },
          "notificationPort" : {
            "type" : "integer"
          },
          "machines" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaConfiguration:ControllerConfiguration:MachineConfiguration",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "type" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

=== Outgoing Topic: `/topic/factory-instance`

declared in `io.github.mbdo.factoryscada.frontend.controller.FactoryScadaController.getFactoryInstance()`

*Request Mapping:* `@MessageMapping("/factory/instance")`

*Send To:* `/topic/factory-instance`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryScadaInstance",
  "properties" : {
    "controllers" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol",
        "properties" : {
          "sendChannelConnected" : {
            "type" : "boolean"
          },
          "receivedChannelConnected" : {
            "type" : "boolean"
          }
        }
      }
    },
    "machines" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:core:AbstractMachine",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "protocol" : {
            "type" : "object",
            "$ref" : "urn:jsonschema:io:github:mbdo:factoryscada:socket:Protocol"
          },
          "rawCommandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "commandNames" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/highBayWarehouse/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.HighBayWarehouseController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/highBayWarehouse/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/indexedLine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.IndexedLineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/indexedLine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/mission-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getFactoryMissionsConfiguration()`

*Request Mapping:* `@MessageMapping("/factoryMission/mission-configuration")`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:MissionConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "commands" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:Command",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "placeholder" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

=== Outgoing Topic: `/topic/mission-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionStatus()`

*Request Mapping:* `@MessageMapping("/factoryMission/status")`

*Send To:* `/topic/mission-status`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "string"
}
----

=== Outgoing Topic: `/topic/mission-configuration`

declared in `io.github.mbdo.factoryscada.frontend.controller.MissionOrchestratorController.getMissionList()`

*Request Mapping:* `@MessageMapping("/factoryMission/list")`

*Send To:* `/topic/mission-configuration`

==== Parameters


==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "missions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:MissionConfiguration",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "commands" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "id" : "urn:jsonschema:io:github:mbdo:factoryscada:domains:factoryscada:dtos:FactoryMissionsConfiguration:Command",
              "properties" : {
                "name" : {
                  "type" : "string"
                },
                "description" : {
                  "type" : "string"
                },
                "placeholder" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/multiProcessingStation/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.MultiProcessingStationController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/multiProcessingStation/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{plcName}/plc-connection-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PlcController.getPlcConnectionStatus()`

*Request Mapping:* `@MessageMapping("/plc/{plcName}/plc-connection")`

*Send To:* `/topic/{plcName}/plc-connection-status`

==== Parameters

- `plcName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:PlcConnectionStatusDto",
  "properties" : {
    "controllerName" : {
      "type" : "string"
    },
    "commandPortConnected" : {
      "type" : "boolean"
    },
    "notificationPortConnected" : {
      "type" : "boolean"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/punchingMachine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.PunchingMachineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/punchingMachine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/sortingLine/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.SortingLineController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/sortingLine/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/command-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getCommandStatus()`

*Request Mapping:* `@MessageMapping("/vacuumGripper/{machineName}/command-status")`

*Send To:* `/topic/{machineName}/command-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:CommandStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "currentCommandRawJSON" : {
      "type" : "string"
    },
    "currentCommandId" : {
      "type" : "string"
    },
    "currentCommandName" : {
      "type" : "string"
    },
    "currentCommandTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackRawJSON" : {
      "type" : "string"
    },
    "commandFeedbackStatus" : {
      "type" : "string"
    },
    "commandFeedbackTimestamp" : {
      "type" : "string"
    },
    "commandFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

=== Outgoing Topic: `/topic/{machineName}/machine-status`

declared in `io.github.mbdo.factoryscada.frontend.controller.VacuumGripperController.getMachineStatus()`

*Request Mapping:* `@MessageMapping("/vacuumGripper/{machineName}/machine-status")`

*Send To:* `/topic/{machineName}/machine-status`

==== Parameters

- `machineName` (String)

==== Response Payload

[source,json]
----
{
  "type" : "object",
  "id" : "urn:jsonschema:io:github:mbdo:factoryscada:frontend:dto:MachineStatusDTO",
  "properties" : {
    "machineName" : {
      "type" : "string"
    },
    "machineFeedbackRawJSON" : {
      "type" : "string"
    },
    "machineFeedbackStatus" : {
      "type" : "string"
    },
    "machineFeedbackTimestamp" : {
      "type" : "string"
    },
    "machineFeedbackInfo" : {
      "type" : "string"
    }
  }
}
----

