# cf. https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[metadata]
name = rppmcontroller
version = 0.1.0
#author = Didier Vojtisek
#author_email = didier.Vojtisek@inria.fr
summary = RevPiPyMachineController Framework project
description_file = README.md
home_page = https://git.rwth-aachen.de/mbdo/mbdo-impl/-/tree/master/rppmcontroller
requires_dist = setuptools
classifier =
# cf. https://pypi.org/classifiers/
    Development Status :: 2 - Pre-Alpha
    Intended Audience :: Developers
    # License :: OSI Approved :: BSD License
    # Operating System :: OS Independent
    # Programming Language :: Python
    # Topic :: Software Development :: Build Tools
    # Topic :: Software Development :: Libraries :: Python Modules
    # Topic :: System :: Archiving :: Packaging


[options]
packages = find:
# TODO see if we can move this require to tests_requires
install_requires =  
    revpimodio2
setup_requires =
    pytest-runner
    wheel
tests_requires =
    pytest

[options.extras_require]
dev =
    pytest
    pylint
    Sphinx
    wheel

[options.packages.find]
exclude = tests

[build_sphinx]
project = RevPiPyMachineController Framework Project
release = 0.1.0
copyright = Copyright 2024 University of Aachen / University of Stuttgart / University of Rennes
config_dir = docs

[aliases]
test=pytest
